server:
  port: 8080

spring:
  application:
    name: currency-converter
  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false

  datasource:
    url: jdbc:h2:mem:currencydb
    driver-class-name: org.h2.Driver
    username: sa
    password: pass

  h2:
    console:
      enabled: true
      path: /cc-console
      settings:
        web-allow-others: false

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: admin
      password: admin123

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG

exchange:
  api:
    base-url: https://api.frankfurter.dev/v1
    timeout: 6000

